"""new fields in user model

Revision ID: 818bb8911161
Revises: 59c6571d1243
Create Date: 2020-02-25 13:54:45.960240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818bb8911161'
down_revision = '59c6571d1243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
